-- 1. Create 'messages' table for the Chat
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  username text not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create 'comments' table for the Comments section
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  context_id text not null, -- e.g., 'u17', 'u19'
  username text not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create 'app_state' table for Data Sync (standings, matches, etc.)
create table if not exists public.app_state (
  id text primary key, -- usually 'global_state'
  config_data jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable Row Level Security (RLS) on all tables
alter table public.messages enable row level security;
alter table public.comments enable row level security;
alter table public.app_state enable row level security;

-- 5. Create Policies (ALLOW ALL for this public demo application)
-- Messages Policies
create policy "Allow public read messages"
on public.messages for select using (true);

create policy "Allow public insert messages"
on public.messages for insert with check (true);

-- Comments Policies
create policy "Allow public read comments"
on public.comments for select using (true);

create policy "Allow public insert comments"
on public.comments for insert with check (true);

-- App State Policies
create policy "Allow public read app_state"
on public.app_state for select using (true);

create policy "Allow public insert/update app_state"
on public.app_state for all using (true);

-- 6. Enable Realtime possibilities
-- Note: You may need to enable Realtime for these tables in the Supabase Dashboard explicitly,
-- but adding them to the publication often helps if the extension is active.
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime for table messages, comments, app_state;
commit;
