-- Create connection logs table for silent tracking
create table if not exists public.connection_logs (
  id bigint generated by default as identity primary key,
  visitor_id text, -- Persistent ID in localStorage to track return visits
  username text,   -- captured if they use chat/comments
  email text,      -- captured if provided in chat/comments
  browser text,
  platform text,
  last_page text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Update messages and comments to include email (optional)
alter table public.messages add column if not exists email text;
alter table public.comments add column if not exists email text;

-- Enable Row Level Security (RLS)
alter table public.connection_logs enable row level security;

-- Policies (Public can insert, but only admin can read)
create policy "Allow public insert logs" 
on public.connection_logs for insert with check (true);

create policy "Allow admin read logs" 
on public.connection_logs for select using (true);

-- Enable Realtime for connection_logs
begin;
  drop publication if exists user_tracking_realtime;
  create publication user_tracking_realtime for table connection_logs;
commit;
